#!/bin/bash
# This script adds new users to an ldap

while IFS='' read -r line || [[ -n "$line" ]]; do
	username=$line
	echo "Adding to the user: $username" 
	echo -e "addprinc $username\nmanager\nmanager\nquit\n" |kadmin.local
done < "$1"
