#!/bin/bash
# This script adds new users to an ldap
#!/bin/bash

touch users.ldif

while IFS='' read -r line || [[ -n "$line" ]]; do
	Upfirst=$(echo "$line" |awk -F"," '{print$1}' )
	Uplast=$(echo "$line" |awk -F"," '{print$2}' )
	firstname=$(echo "$line" |awk -F"," '{print$1}' |tr '[[:upper:]]' '[[:lower:]]')
	lastname=$(echo "$line" |awk -F"," '{print$2}' |tr '[[:upper:]]' '[[:lower:]]')
	idnum=$(echo "$line" |awk -F"," '{print$3}' )
	firstlower=$(echo `expr substr $firstname 1 2`)
	secndlower=$(echo `expr substr $lastname 1 2`)
	uid=$firstlower$secndlower$idnum
	uidNumber=200
	password=$firstlower$secndlower$idnum
	cn="$Upfirst $Uplast"
# Entering data into the file users.ldif
	echo "dn: cn=$cn,ou=People,dc=example,dc=com" >> users.ldif
	echo "uid: $uid" >> users.ldif
	echo "cn: $uid" >> users.ldif
	echo "objectClass: posixAccount" >> users.ldif
	echo "userPassword: $password" >> users.ldif
	echo "objectClass: account" >> users.ldif
	echo "loginShell: /bin/bash" >> users.ldif
	echo "uidNumber: $idnum" >> users.ldif
	echo "gidNumber: 100" >> users.ldif
	echo "homeDirectory: /home/guest/$uid" >> users.ldif
	echo "gecos: $uid" >> users.ldif
	echo "" >> users.ldif
done < "$1"

# Loading users to ldap

ldapadd -x -w passwd -D cn=Manager,dc=example,dc=com -f users.ldif
